# Generated by Django 2.0.4 on 2018-04-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='conten',
            new_name='content',
        ),
    ]
